# build
url: "https://www.purewaterefluentes.com.br"
description: "Purewater Efluentes - Produtos químicos para tratamento de água, efluentes industriais e piscinas. Equipamentos e serviços ambientais. São Paulo, SP."
markdown: kramdown
permalink: none
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
  - uplift/
layouts_dir: ./_layouts
sass:
  sass_dir: website/_scss
  style: compressed
# compress layout in _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# Google analytics
google_analytics: 'UA-50083848-3'
# theme
purewater:
  name: Purewater Efluentes
  author:
    name: Marcelo Garcia
  lang: pt
  topbar:
    toggle: Menu
    right:
      - name: Produtos
        url: /produtos/
      - name: Serviços
        url: /servicos/
      - name: Equipamentos
        url: /equipamentos/
      - name: Contato
        url: /contato/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap