# build
markdown: kramdown
permalink: /blog/:year/:title/
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts_dir: ./_layouts
sass:
  sass_dir: website/_scss
  style: compressed
# compress layout in _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
purewater:
  name: Purewater Efluentes
  author:
    name: Marcelo Garcia
  lang: pt
  topbar:
    toggle: Menu
    right:
      - name: Produtos
        url: /produtos/
      - name: Serviços
        url: /servicos/
      - name: Equipamentos
        url: /equipamentos/
      - name: Contato
        url: /contato/