{% if site.google_analytics %}
<script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ site.google_analytics }}');
  gtag('config', 'AW-1041562649');

  function gtagReportConversionContactForm() {
    gtag('event', 'conversion', {'send_to': 'AW-1041562649/y4qfCJ3O1I0CEJn40_AD'});
  }

  function gtagReportConversionEmailLink(url) {
    var callback = function () {
      if (typeof(url) != 'undefined') { window.location = url; }
    };
    gtag('event', 'conversion', {'send_to': 'AW-1041562649/58TSCIn_-qADEJn40_AD', 'event_callback': callback});
    return false;
  }

  function gtagReportConversionWhatsapp(url) {
    var callback = function () {
      if (typeof(url) != 'undefined') { window.location = url; }
    };
    gtag('event', 'conversion', {'send_to': 'AW-1041562649/is9gCNHz-qADEJn40_AD', 'event_callback': callback});
    return false;
  }
</script>
{% endif %}
